import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Sidebar } from "@/components/Sidebar";
import { AddTransactionModal } from "@/components/AddTransactionModal";
import { AddAccountModal } from "@/components/AddAccountModal";
import { TransactionModalProvider } from "@/context/TransactionModalContext";
import { AccountModalProvider } from "@/context/AccountModalContext";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-br"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased dark`}
      suppressHydrationWarning
    >
      <body className="min-h-full bg-black text-white font-sans selection:bg-violet-500/30" suppressHydrationWarning>
        <TransactionModalProvider>
          <AccountModalProvider>
            <div className="flex min-h-screen">
              <Sidebar />
              <main className="flex-1 md:pl-64 min-h-screen relative">
                {/* Background elements */}
                <div className="fixed inset-0 overflow-hidden pointer-events-none -z-10">
                  <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-violet-600/20 blur-[120px] rounded-full animate-pulse" />
                  <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-fuchsia-600/20 blur-[120px] rounded-full" />
                </div>
                {children}
              </main>
            </div>
            <AddTransactionModal />
            <AddAccountModal />
          </AccountModalProvider>
        </TransactionModalProvider>
      </body>
    </html>
  );
}
